# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Clean Workspace
        # You may pin to the exact commit or the version.
        # uses: AutoModality/action-clean@d004b47eb728f2a83316fc70ba9a62ef97278013
        uses: AutoModality/action-clean@v1.1.0
  

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Angular Deploy GitHub Pages Actions
      - name: Angular Deploy GitHub Pages Actions
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.1
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          angular_dist_build_folder: dist/tursoft-angular-components
          base_href: tursoft-angular-components
      #- name: GitHub Pages
      #  uses: crazy-max/ghaction-github-pages@v2.1.2
      #  with:
      #    build_dir: dist\tursoft-angular-components
